### PR TITLE
Issue #681: More obvious loader

### PR DESCRIPTION
**Pull request by dustinleblanc**

### CODE REVIEW

**Comment by pirog** [comment]
@reynoldsalec can i get a second opinion here? I definitely think we want (need) the page to be blocking so that there is a more familiar page loading experience but this is not really what i had in mind and doesnt seem like a good experience either.

I also noticed that on the large amount of pages that ive "made faster" the current loader isnt as confusing so i'm not sure if there is a "general optimization" pass we could do that would both make this better and also make our site faster.

**Comment by dustinleblanc** [comment]
It definitely looks better on slower pages and worse on faster ones, maybe we could build in a delay so a loader only comes up if the page load is taking too long

**Comment by pirog** [comment]
ping @reynoldsalec for some feedback

**Comment by reynoldsalec** [comment]
This seems a bit jarring; to me it doesn't feel congruous with the design of the site and breaks my expectations of how a "fast" website should feel. If I see a blank page loading for a couple seconds I assume my internet is bad. If I see a loader for a couple seconds, I assume the website is at fault.

Agree with @pirog that general optimization of slow pages will be the best all-around solution. The only other thing I can think of is limiting the "loading" text to the content area. Header menus update instantly, so the biggest confusion is when content doesn't load into the site and I end up looking at old content when the rest of my page seems to have updated.

This is kind of a crazy idea, but we could also just blank out the page as the overlay loader to recreate a "default" web experience...but on long page loads guessing that still looks really bad.

**Comment by reynoldsalec** [comment]
Yeah, tried out a blank white page; looked pretty bad with a long load time.

Guessing this is known knowledge, but the /poems, /poets, etc. list pages seemed to have some of the most severe performance issues that I was seeing anecdotally.

**Comment by pirog** [comment]
It’s worth noting that the list pages are going to load significantly
faster on master than on a PR branch because of caching and resources so
any testing you do should happen on master

**Comment by dustinleblanc** [comment]
I'm going to go ahead and close this as whatever the desired behavior, it's not this :)

**Comment by pirog** [comment]
@dustinleblanc, my bad, @reynoldsalec and i didnt get you up to speed on this one before you took the helm. 

I think the plan we had for now was "wait and see" until we are very pre-launch. It's possible our production performance just makes this a non issue, if it doesnt then @reynoldsalec was suggesting using the loader just in the "main content area" so its not as ... eye bleedy. 

So i'm going to reopen this and we can reassess closer to launch.

**Comment by dustinleblanc** [comment]
@pirog okay, sounds fine then

**Comment by pirog** [comment]
@dustinleblanc word, sorry for failing to knowledge share that to you!

**Pull request closed without merging**
