### PR TITLE
Poet Card styling

### PR DESCRIPTION
**Pull request by soniktrooth**
Deck component still incoming

### CODE REVIEW

**Comment by soniktrooth** [comment]
Travis hates me.

**Comment by soniktrooth** [comment]
What did I ever do to you Travis?

**Comment by soniktrooth** [comment]
ok deck component in place too. We are GTG

**Comment by dustinleblanc** [comment]
Great work @soniktrooth! I saw one thing I might change here, but I don't see it as a blocker.

**Pull request merged**
